<?php $intl = $this->getController()->translator; ?>

<?php if ($this->param("process") == "success"): ?>

	<?php if (is_array($names)): ?>
		<div class="alert alert-success" role="alert">
			<i class="fas fa-check"></i> <?= $intl->translate("Files uploaded successfully") ?><br />
			<?php
				$_names = implode("<br />", $names);
				echo "<strong>$_names</strong>";
			?>
		</div>
	<?php else: ?>
		<div class="alert alert-success">
			<strong><span class="glyphicon glyphicon-ok"></span></strong> Se cargó correctamente el archivo <strong><?= $this->param("name") ?></strong>
		</div>
	<?php endif; ?>

<?php elseif ($this->param("process") == "warning"): ?>

	<div class="alert alert-warning" role="alert">
		<i class="fas fa-exclamation"></i> &nbsp;<?= $intl->translate($this->param("message")) ?>
	</div>

	<?php if ($this->isParam("messages") && count($this->param("messages"))): ?>
		<?php foreach($this->param("messages") as $input => $messages): ?>
			<?php $lbl = $this->param("validator")->getOption($input, "label"); ?>

				<h5><strong><?= $intl->translate($lbl) ?></strong></h5>
				<ol>
					<?php foreach($messages as $code => $message): ?>
						<li><?= $message ?></li>
					<?php endforeach; ?>
				</ol>

		<?php endforeach; ?>
	<?php endif; ?>

<?php endif; ?>